const CLIP_AUDIO_ASSETS: Record<string, number> = {
  'clips/clip1.mp3': require('../../clips/clip1.mp3'),
  'clips/clip2.mp3': require('../../clips/clip2.mp3'),
  'clips/clip3.mp3': require('../../clips/clip3.mp3'),
  'clips/clip4.mp3': require('../../clips/clip4.mp3'),
  'clips/clip5.mp3': require('../../clips/clip5.mp3'),
  'clips/clip6.mp3': require('../../clips/clip6.mp3'),
  'clips/clip7.mp3': require('../../clips/clip7.mp3'),
  'clips/clip8.mp3': require('../../clips/clip8.mp3'),
  'clips/clip9.mp3': require('../../clips/clip9.mp3'),
  'clips/clip10.mp3': require('../../clips/clip10.mp3'),
  'clips/clip11.mp3': require('../../clips/clip11.mp3'),
  'clips/clip12.mp3': require('../../clips/clip12.mp3'),
  'clips/clip13.mp3': require('../../clips/clip13.mp3'),
  'clips/clip14.mp3': require('../../clips/clip14.mp3'),
  'clips/clip15.mp3': require('../../clips/clip15.mp3'),
  'clips/clip16.mp3': require('../../clips/clip16.mp3'),
  'clips/clip17.mp3': require('../../clips/clip17.mp3'),
  'clips/clip18.mp3': require('../../clips/clip18.mp3'),
  'clips/clip19.mp3': require('../../clips/clip19.mp3'),
  'clips/clip20.mp3': require('../../clips/clip20.mp3'),
  'clips/clip21.mp3': require('../../clips/clip21.mp3'),
  'clips/clip22.mp3': require('../../clips/clip22.mp3'),
  'clips/clip23.mp3': require('../../clips/clip23.mp3'),
  'clips/clip24.mp3': require('../../clips/clip24.mp3'),
  'clips/clip25.mp3': require('../../clips/clip25.mp3'),
  'clips/clip26.mp3': require('../../clips/clip26.mp3'),
  'clips/clip27.mp3': require('../../clips/clip27.mp3'),
  'clips/clip28.mp3': require('../../clips/clip28.mp3'),
  'clips/clip29.mp3': require('../../clips/clip29.mp3'),
  'clips/clip30.mp3': require('../../clips/clip30.mp3'),
  'clips/clip31.mp3': require('../../clips/clip31.mp3'),
  'clips/clip32.mp3': require('../../clips/clip32.mp3'),
  'clips/clip33.mp3': require('../../clips/clip33.mp3'),
  'clips/clip34.mp3': require('../../clips/clip34.mp3'),
  'clips/clip35.mp3': require('../../clips/clip35.mp3'),
  'clips/clip36.mp3': require('../../clips/clip36.mp3'),
  'clips/clip37.mp3': require('../../clips/clip37.mp3'),
  'clips/clip38.mp3': require('../../clips/clip38.mp3'),
};

export function getBundledClipAudioAsset(raw: string) {
  return CLIP_AUDIO_ASSETS[raw] || CLIP_AUDIO_ASSETS[`clips/${raw.replace(/^clips\//, '')}`] || null;
}
